
services:

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin!12345
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: P@ssw0rd
    ports:
      - 3306:3306
    volumes:
      - /home/xuyuandong/workspace/mysql/data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080