version: "3.0"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin!12345
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - /home/xuyuandong/workspace/postgres/data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080