version: "3.0"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin!12345
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - /home/ubuntu/workspace/postgres/data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080
    
  golang:
    image: golang:alpine3.18
    volumes:
      - /home/ubuntu/workspace:/var/workspace
    command: top -b
    